model_params:
  name: "HVAE"
  in_channels: 3
  latent1_dim: 64
  latent2_dim: 64
  pseudo_input_size: 128

data_params:
  root: "./Data/"
  batch_size: 64
  patch_size: 64
  num_workers: 2
  pin_memory: false

exp_params:
  LR: 0.0005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  manual_seed: 1265

trainer_params:
  max_epochs: 10
  patience: 2
  best_path: "./logs/hvae0/best"
  kld_weight: 0.00025
  save_dir: "./logs/hvae0/"